version: '3.8'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - my_network

networks:
  my_network:
    external: true