version: '3.8'

services:
  auth-service:
    container_name: auth-service
    image: auth-service-image:1.0
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_auth_db:5432/UserAuthStorage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - JWT_EXPIRATION=604800
      - JWT_SECRET=superSecret
      - JWT_HEADER=Authorization
      - DISCOVERY_SERVER_URL=http://discovery-server:8761/eureka
      - ZIPKIN_URL=http://zipkin:9411
    depends_on:
      - user_auth_db
    networks:
      - my_network

  user_auth_db:
    container_name: user_auth_db
    image: postgres:10.4
    environment:
      - POSTGRES_DB=UserAuthStorage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - "5433:5432"
    networks:
      - my_network

networks:
  my_network:
    external: true